### ISSUE TITLE
seamless exec into basic databases

### ISSUE THREAD

**Issue by dmi3coder** [in-jex/docker-compose-context#16]
Provide seamless exec into databases:
1. If pod is one of the images marked as a database - treat the service as a database
2. If the service is a database, instead of exec(or maybe separate command `dbexec`?) try to establish connection from credentials provided in a metadata

e.g: we have next service in docker-compose file
```
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
```
When we do `dbexec`, we exec into the instance, run the `psql` command(and maybe install if it's missing), and provide the database shell right away
